name: Publish Library

on:
  push:
    tags:
      - 'v*'   # e.g., push v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
        working-directory: ./  # <-- optional, defaults to repo root
      - run: npm run build
        working-directory: ./
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./